#pubspec.yaml

name: viajes_ai
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.10.0
  flutter_dotenv: ^6.0.0
  flutter_lints: ^5.0.0
  http: ^1.5.0
  flutter_markdown: ^0.7.7+1
  intl: ^0.19.0
  google_fonts: ^6.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - .env